import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ApolloWrapper } from "@/components/ApolloWrapper";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { auth, signOut } from "@/auth";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const user = session?.user.id;
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background overflow-x-hidden font-sans antialiased",
          fontSans.variable
        )}
      >
        <nav className="fixed inset-x-0 top-0 z-20 bg-white z-50 shadow-sm dark:bg-gray-950/90 border-b-2 border-solid border-black">
          <div className="w-full max-w-7xl mx-auto px-4">
            <div className="flex justify-between h-14 items-center">
              <Link href="/" className="flex items-center" prefetch={false}>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
                </svg>
                <span className="sr-only">Acme Inc</span>
              </Link>
              <nav className="hidden md:flex gap-4">
                <Link
                  href="/wishlist"
                  className="font-medium flex items-center text-sm transition-colors hover:underline"
                  prefetch={false}
                >
                  Your Wishlist
                </Link>
              </nav>
              {!user ? (
                <div className="flex items-center gap-4">
                  <Link href="/signin">
                    <Button variant="outline" size="sm">
                      Sign in
                    </Button>
                  </Link>
                  <Link href="/signup">
                    <Button size="sm">Sign up</Button>
                  </Link>
                </div>
              ) : (
                <div className="flex items-center space-x-4  rounded-lg  p-4">

                  <form
                    action={async () => {
                      "use server";
                      await signOut({ redirectTo: "/signin" });
                    }}
                  >
                    <button
                      type="submit"
                      className="px-4 py-2 bg-red-600 text-white text-sm font-medium rounded-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition duration-150 ease-in-out"
                    >
                      Sign Out
                    </button>
                  </form>
                </div>
              )}
            </div>
          </div>
        </nav>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
