import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ApolloWrapper } from "@/components/ApolloWrapper";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <nav className="fixed inset-x-0 top-0 z-20 bg-white z-50 shadow-sm dark:bg-gray-950/90 border-b-2 border-solid border-black">
        <div className="w-full max-w-7xl mx-auto px-4">
          <div className="flex justify-between h-14 items-center">
            <Link href="#" className="flex items-center" prefetch={false}>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
              </svg>
              <span className="sr-only">Acme Inc</span>
            </Link>
            <nav className="hidden md:flex gap-4">
              <Link
                href="/wishlist"
                className="font-medium flex items-center text-sm transition-colors hover:underline"
                prefetch={false}
              >
                Your Wishlist
              </Link>
              
              
            </nav>
            <div className="flex items-center gap-4">
              <Link href="/signin">
              <Button variant="outline" size="sm">
                Sign in
              </Button>
              </Link>
              <Link href="/signup">
              <Button size="sm">Sign up</Button>
              </Link>
            </div>
          </div>
        </div>
      </nav>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
